//! AutomatedTransaction generated based on the registered active automation task.

use crate::errors::SupraExtensionError;
use crate::value_or_error;
use crate::TaskMetadata;
use alloy::eips::eip2930::AccessList;
use alloy::primitives::{Address, Bytes, ChainId, B256, U256};
use alloy_consensus::transaction::Transaction;
use alloy_eips::eip2718::Typed2718;
use alloy_sol_types::SolType;
use context::transaction::{AccessListItem, SignedAuthorization};
use context::TransactionType;
use derive_getters::{Dissolve, Getters};
use derive_more::Constructor;
use primitives::TxKind;
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;

/// Represents automation task predicate details.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub struct TaskPredicate {
    /// Contract address holding predicate function
    pub address: Address,
    /// Encoded predicate function pointer and inputs
    pub input: Bytes,
}

impl TryFrom<&[u8]> for TaskPredicate {
    type Error = SupraExtensionError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        if value.is_empty() {
            return Ok(Self::default());
        }
        type PredicateType = (
            alloy_sol_types::sol_data::Address,
            alloy_sol_types::sol_data::Bytes,
        );
        let (address, input) = PredicateType::abi_decode_sequence(value).map_err(|e| {
            SupraExtensionError::PayloadDecode {
                error: e,
                payload: "predicate".to_owned(),
            }
        })?;
        Ok(Self { address, input })
    }
}

/// Supported automation task predicates
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
pub enum AutomationTaskPredicate {
    /// Represents always true predicate
    #[default]
    Bypass,
    /// Predicate to be executed.
    Predicate(TaskPredicate),
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
#[repr(u8)]
/// Automated transaction type corresponding automation task type.
pub enum AutomatedTransactionType {
    /// User submitted automation task based
    #[default]
    UST = 0,
    /// Governance submitted/authorized automation task based. Will be gasless transaction
    GST,
}

impl TryFrom<u8> for AutomatedTransactionType {
    type Error = SupraExtensionError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::UST),
            1 => Ok(Self::GST),
            _ => Err(Self::Error::InvalidAutomationTaskTypeValue(value)),
        }
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
/// Automated transaction generated by node runtime based on the registered active automation task.
pub struct AutomatedTransaction {
    /// Height of the block in scope of which this transaction is being executed.
    pub block_height: u64,
    /// Hash of the transaction which registered an automation task based on which this transaction is created.
    pub registration_hash: B256,
    /// Owner address of the automation task, the source of this transaction.
    pub sender: Address,
    /// Type of the automated transaction.
    pub txn_type: AutomatedTransactionType,
    /// Chain id.
    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity"))]
    pub chain_id: ChainId,
    /// A scalar value equal to the automation task index based on which this transaction is created.
    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity"))]
    pub nonce: u64,
    /// A scalar value equal to the maximum
    /// amount of gas that should be used in executing
    /// this transaction. This is paid up-front, before any
    /// computation is done and may not be increased
    /// later; formally Tg.
    #[cfg_attr(
        feature = "serde",
        serde(with = "alloy_serde::quantity", rename = "gas", alias = "gasLimit")
    )]
    pub gas_limit: u64,
    /// A scalar value equal to the maximum
    /// amount of gas that should be used in executing
    /// this transaction.
    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity"))]
    pub max_fee_per_gas: u128,
    /// The 160-bit address of the message call’s recipient or, for a contract creation
    /// transaction, ∅, used here to denote the only member of B0 ; formally Tt.
    #[cfg_attr(feature = "serde", serde(default))]
    pub to: Address,
    /// A scalar value equal to the number of Wei to
    /// be transferred to the message call’s recipient or,
    /// in the case of contract creation, as an endowment
    /// to the newly created account; formally Tv.
    pub value: U256,
    /// The accessList specifies a list of addresses and storage keys;
    /// these addresses and storage keys are added into the `accessed_addresses`
    /// and `accessed_storage_keys` global sets (introduced in EIP-2929).
    /// A gas cost is charged, though at a discount relative to the cost of
    /// accessing outside the list.
    // Deserialize with `alloy_serde::null_as_default` to also accept a `null` value
    // instead of an (empty) array. This is due to certain RPC providers (e.g., Filecoin's)
    // sometimes returning `null` instead of an empty array `[]`.
    // More details in <https://github.com/alloy-rs/alloy/pull/2450>.
    #[cfg_attr(
        feature = "serde",
        serde(deserialize_with = "alloy_serde::null_as_default")
    )]
    pub access_list: AccessList,
    /// Input: An unlimited size byte array specifying the
    /// input data of the message call.
    pub input: Bytes,

    /// Predicate controlling task execution.
    /// If predicate execution is successful and true the main action will be executed.
    pub predicate: AutomationTaskPredicate,
}

impl Transaction for AutomatedTransaction {
    #[inline]
    fn chain_id(&self) -> Option<ChainId> {
        Some(self.chain_id)
    }

    #[inline]
    fn nonce(&self) -> u64 {
        self.nonce
    }

    #[inline]
    fn gas_limit(&self) -> u64 {
        self.gas_limit
    }

    #[inline]
    fn gas_price(&self) -> Option<u128> {
        None
    }

    #[inline]
    fn max_fee_per_gas(&self) -> u128 {
        self.max_fee_per_gas
    }

    #[inline]
    fn max_priority_fee_per_gas(&self) -> Option<u128> {
        Some(0)
    }

    #[inline]
    fn max_fee_per_blob_gas(&self) -> Option<u128> {
        None
    }

    #[inline]
    fn priority_fee_or_price(&self) -> u128 {
        0
    }

    fn effective_gas_price(&self, base_fee: Option<u64>) -> u128 {
        alloy_eips::eip1559::calc_effective_gas_price(self.max_fee_per_gas, 0, base_fee)
    }

    #[inline]
    fn is_dynamic_fee(&self) -> bool {
        true
    }

    #[inline]
    fn kind(&self) -> TxKind {
        TxKind::Call(self.to)
    }

    #[inline]
    fn is_create(&self) -> bool {
        false
    }

    #[inline]
    fn value(&self) -> U256 {
        self.value
    }

    #[inline]
    fn input(&self) -> &Bytes {
        &self.input
    }

    #[inline]
    fn access_list(&self) -> Option<&AccessList> {
        Some(&self.access_list)
    }

    #[inline]
    fn blob_versioned_hashes(&self) -> Option<&[B256]> {
        None
    }

    #[inline]
    fn authorization_list(&self) -> Option<&[SignedAuthorization]> {
        None
    }
}

impl Typed2718 for AutomatedTransaction {
    fn ty(&self) -> u8 {
        TransactionType::Custom as u8
    }
}

impl AutomatedTransaction {
    /// Returns true if automated transaction is gas-less, otherwise false.
    /// GST type transactions are considered as gas-less.
    pub fn is_gasless(&self) -> bool {
        matches!(self.txn_type, AutomatedTransactionType::GST)
    }
}

/// Evm automated transaction with priority to be scheduled for execution.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct AutomatedTransactionDetails {
    /// Transaction details
    pub txn: AutomatedTransaction,
    /// Priority of the automated transaction to be scheduled.
    /// The low value indicates higher priority.
    pub priority: u64,
}

impl Ord for AutomatedTransactionDetails {
    fn cmp(&self, other: &Self) -> Ordering {
        let left_type = &self.txn.txn_type;
        let right_type = &other.txn.txn_type;
        if left_type == right_type {
            self.priority.cmp(&other.priority)
        } else {
            left_type.cmp(right_type)
        }
    }
}
impl PartialOrd for AutomatedTransactionDetails {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

type AccessListItemTy = (
    alloy_sol_types::sol_data::Address,
    alloy_sol_types::sol_data::Array<alloy_sol_types::sol_data::FixedBytes<32>>,
);
type AccessListTy = alloy_sol_types::sol_data::Array<AccessListItemTy>;
type ExpandedPayloadTy = (
    alloy_sol_types::sol_data::Uint<256>,
    alloy_sol_types::sol_data::Address,
    alloy_sol_types::sol_data::Bytes,
    AccessListTy,
);

/// Evm automation task execution payload.
#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    Getters,
    Dissolve,
    Constructor,
)]
pub struct TaskPayload {
    to: Address,
    value: U256,
    input: Bytes,
    access_list: AccessList,
}

impl TaskPayload {
    /// Generates random [`TaskPayload`] for testing propose only.
    pub fn random() -> Self {
        TaskPayload {
            to: Address::random(),
            value: U256::random(),
            input: Bytes::from(b"test"),
            access_list: AccessList::default(),
        }
    }
}

impl TryFrom<&[u8]> for TaskPayload {
    type Error = SupraExtensionError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        let (value, to, input, access_list) =
            ExpandedPayloadTy::abi_decode(value).map_err(|e| {
                SupraExtensionError::PayloadDecode {
                    error: e,
                    payload: "task action".to_owned(),
                }
            })?;
        let access_items = access_list
            .into_iter()
            .map(|(address, storage_keys)| AccessListItem {
                address,
                storage_keys,
            })
            .collect();
        Ok(Self {
            to,
            value,
            access_list: AccessList(access_items),
            input,
        })
    }
}

/// Automation task state in native layer
#[derive(Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
enum AutomationTaskState {
    Pending = 0,
    Active = 1,
    Cancelled = 2,
}

impl TryFrom<u8> for AutomationTaskState {
    type Error = SupraExtensionError;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Pending),
            1 => Ok(Self::Active),
            2 => Ok(Self::Cancelled),
            _ => Err(SupraExtensionError::InvalidAutomationTaskStateValue(value)),
        }
    }
}

/// [`AutomatedTransactionBuilder`] result
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BuildResult {
    /// Success result wrapping [`AutomatedTransactionDetails`]
    Success(AutomatedTransactionDetails),
    /// Build failure due to gas-price limit surpass.
    GasPriceLimitExceeded {
        /// Task index for which error is observed.
        task_index: u64,
        /// Gas price specified for the transaction.
        value: u128,
        /// Gas price threshold specified for the automation task during registration.
        threshold: u128,
    },
}

/// Builder for [`AutomatedTransactionDetails`]
/// All properties are mandatory to be set for successful automated transaction build.
/// The following values fall back to agreed defaults if not specified:
///   - priority - defaults to task-index
///   - access_list - default to empty access-list
///   - value - defaults to 0
#[derive(Clone, Debug, Getters)]
pub struct AutomatedTransactionBuilder {
    block_height: Option<u64>,
    chain_id: Option<ChainId>,
    gas_limit: Option<u64>,
    gas_price: Option<u128>,
    gas_price_cap: Option<u128>,
    registration_hash: Option<B256>,
    task_index: Option<u64>,
    expiry_timestamp: Option<u64>,
    owner: Option<Address>,
    typ: Option<AutomatedTransactionType>,
    priority: Option<u64>,

    to: Option<Address>,
    value: Option<U256>,
    access_list: Option<AccessList>,
    input: Option<Bytes>,
    predicate: Option<TaskPredicate>,
}

#[allow(missing_docs)]
impl AutomatedTransactionBuilder {
    pub fn new() -> Self {
        Self {
            block_height: None,
            chain_id: None,
            gas_limit: None,
            gas_price: None,
            gas_price_cap: None,
            registration_hash: None,
            task_index: None,
            expiry_timestamp: None,
            owner: None,
            typ: None,
            priority: None,
            to: None,
            value: Some(U256::from(0)),
            access_list: Some(AccessList::default()),
            input: None,
            predicate: None,
        }
    }

    pub fn with_block_height(mut self, block_height: u64) -> Self {
        self.block_height = Some(block_height);
        self
    }

    pub fn with_chain_id(mut self, chain_id: ChainId) -> Self {
        self.chain_id = Some(chain_id);
        self
    }

    pub fn with_gas_limit(mut self, gas_limit: u64) -> Self {
        self.gas_limit = Some(gas_limit);
        self
    }

    pub fn with_gas_price(mut self, gas_price: u128) -> Self {
        self.gas_price = Some(gas_price);
        self
    }

    pub fn with_gas_price_cap(mut self, gas_price_cap: u128) -> Self {
        self.gas_price_cap = Some(gas_price_cap);
        self
    }

    pub fn with_registration_hash(mut self, registration_hash: B256) -> Self {
        self.registration_hash = Some(registration_hash);
        self
    }

    pub fn with_task_index(mut self, task_index: u64) -> Self {
        self.task_index = Some(task_index);
        self
    }

    pub fn with_expiry_timestamp(mut self, expiry_timestamp: u64) -> Self {
        self.expiry_timestamp = Some(expiry_timestamp);
        self
    }

    pub fn with_owner(mut self, owner: Address) -> Self {
        self.owner = Some(owner);
        self
    }
    pub fn with_typ(mut self, typ: AutomatedTransactionType) -> Self {
        self.typ = Some(typ);
        self
    }

    pub fn with_priority(mut self, priority: u64) -> Self {
        self.priority = Some(priority);
        self
    }

    pub fn with_to(mut self, to: Address) -> Self {
        self.to = Some(to);
        self
    }

    pub fn with_value(mut self, value: U256) -> Self {
        self.value = Some(value);
        self
    }

    pub fn with_access_list(mut self, access_list: AccessList) -> Self {
        self.access_list = Some(access_list);
        self
    }

    pub fn with_input(mut self, input: Bytes) -> Self {
        self.input = Some(input);
        self
    }

    pub fn with_predicate(mut self, predicate: TaskPredicate) -> Self {
        self.predicate = Some(predicate);
        self
    }

    pub fn build(self) -> Result<BuildResult, SupraExtensionError> {
        let Self {
            block_height,
            chain_id,
            gas_limit,
            gas_price,
            gas_price_cap,
            registration_hash,
            task_index,
            expiry_timestamp: _,
            owner,
            typ,
            priority,
            to,
            value,
            access_list,
            input,
            predicate,
        } = self;
        let typ = value_or_error!(AutomatedTransactionBuilder, "type", typ);
        let block_height =
            value_or_error!(AutomatedTransactionBuilder, "block_height", block_height);
        let chain_id = value_or_error!(AutomatedTransactionBuilder, "chain_id", chain_id);
        let gas_limit = value_or_error!(AutomatedTransactionBuilder, "gas_limit", gas_limit);
        let gas_price_cap =
            value_or_error!(AutomatedTransactionBuilder, "gas_price_cap", gas_price_cap);
        // GST based automated transaction are not charged, so the gas price is not mandatory and default to 0.
        let gas_price = match typ {
            AutomatedTransactionType::UST => {
                value_or_error!(AutomatedTransactionBuilder, "gas_price", gas_price)
            }
            AutomatedTransactionType::GST => 0,
        };
        let registration_hash = value_or_error!(
            AutomatedTransactionBuilder,
            "registration_hash",
            registration_hash
        );
        let task_index = value_or_error!(AutomatedTransactionBuilder, "task_index", task_index);
        let owner = value_or_error!(AutomatedTransactionBuilder, "owner", owner);
        let priority = priority.unwrap_or(task_index);
        let to = value_or_error!(AutomatedTransactionBuilder, "to", to);
        let value = value_or_error!(AutomatedTransactionBuilder, "value", value);
        let access_list = value_or_error!(AutomatedTransactionBuilder, "access_list", access_list);
        let input = value_or_error!(AutomatedTransactionBuilder, "input", input);
        if typ == AutomatedTransactionType::UST && gas_price_cap < gas_price{
            return Ok(BuildResult::GasPriceLimitExceeded {
                task_index,
                value: gas_price,
                threshold: gas_price_cap,
            });
        }
        let txn = AutomatedTransaction {
            block_height,
            registration_hash,
            sender: owner,
            txn_type: typ,
            chain_id,
            nonce: task_index,
            gas_limit,
            max_fee_per_gas: gas_price,
            to,
            value,
            access_list,
            input,
            predicate: predicate
                .map(AutomationTaskPredicate::Predicate)
                .unwrap_or_default(),
        };
        Ok(BuildResult::Success(AutomatedTransactionDetails {
            txn,
            priority,
        }))
    }
}

/// Constructs [`AutomatedTransactionBuilder`] from automation task details loaded from chain state.
/// Fails if:
///   - inner payload cannot be deserialized based on the  [`ExpandedPayloadTy`] schema
///   - Loaded task is not in active state (Active | Cancelled)
impl TryFrom<TaskMetadata> for AutomatedTransactionBuilder {
    type Error = SupraExtensionError;

    fn try_from(value: TaskMetadata) -> Result<Self, Self::Error> {
        let TaskMetadata {
            maxGasAmount,
            gasPriceCap,
            automationFeeCapForCycle: _,
            depositFee: _,
            txHash,
            taskIndex,
            registrationTime: _,
            expiryTime,
            priority,
            taskType,
            owner,
            taskState,
            payloadTx,
            predicate,
            auxData: _,
        } = value;

        if AutomationTaskState::try_from(taskState)? == AutomationTaskState::Pending {
            return Err(SupraExtensionError::InvalidAutomationTaskStateForBuilder);
        }
        let typ = AutomatedTransactionType::try_from(taskType)?;

        let (to, value, input, access_list) = TaskPayload::try_from(payloadTx.as_ref())?.dissolve();
        let predicate = TaskPredicate::try_from(predicate.as_ref())?;
        let builder = Self::new()
            .with_gas_price_cap(gasPriceCap)
            .with_gas_limit(maxGasAmount as u64)
            .with_gas_price_cap(gasPriceCap)
            .with_registration_hash(txHash)
            .with_task_index(taskIndex)
            .with_expiry_timestamp(expiryTime)
            .with_owner(owner)
            .with_to(to)
            .with_value(value)
            .with_input(input)
            .with_access_list(access_list)
            .with_typ(typ)
            .with_priority(priority)
            .with_predicate(predicate);
        Ok(builder)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::{address, b256, Address, B256, Bytes, U256};
    use alloy_consensus::transaction::Transaction;
    use alloy_sol_types::SolType;
    use crate::{errors::SupraExtensionError, TaskMetadata};
    use crate::transactions::automated_transaction::{ExpandedPayloadTy, TaskPredicate};
    use alloy::hex;

    type PredicateType = (
        alloy_sol_types::sol_data::Address,
        alloy_sol_types::sol_data::Bytes,
    );

    const OWNER: Address = address!("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
    const TO: Address = address!("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb");
    const CHAIN_ID: u64 = 6;
    const BLOCK_HEIGHT: u64 = 200;
    const TASK_INDEX: u64 = 7;
    const GAS_LIMIT: u64 = 500_000;
    const GAS_PRICE: u128 = 1_000;
    const GAS_PRICE_CAP: u128 = 2_000;
    const REG_HASH: B256 = b256!("0101010101010101010101010101010101010101010101010101010101010101");

    fn encode_payload(value: U256, to: Address, input: &[u8]) -> Bytes {
        Bytes::from(ExpandedPayloadTy::abi_encode(&(
            value,
            to,
            Bytes::from(input.to_vec()),
            vec![] as Vec<(Address, Vec<alloy::primitives::B256>)>,
        )))
    }

    fn encode_predicate(addr: Address, input: &[u8]) -> Bytes {
        Bytes::from(PredicateType::abi_encode_sequence(&(
            addr,
            Bytes::from(input.to_vec()),
        )))
    }

    fn base_task_metadata(task_state: u8, task_type: u8) -> TaskMetadata {
        TaskMetadata {
            maxGasAmount: GAS_LIMIT as u128,
            gasPriceCap: GAS_PRICE_CAP,
            automationFeeCapForCycle: 0,
            depositFee: 0,
            txHash: REG_HASH,
            taskIndex: TASK_INDEX,
            registrationTime: 0,
            expiryTime: 0,
            priority: TASK_INDEX,
            owner: OWNER,
            taskType: task_type,
            taskState: task_state,
            payloadTx: encode_payload(U256::ZERO, TO, b"call"),
            predicate: Bytes::default(),
            auxData: vec![],
        }
    }

    fn base_ust_builder() -> AutomatedTransactionBuilder {
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST)
            .with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID)
            .with_gas_limit(GAS_LIMIT)
            .with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP)
            .with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX)
            .with_owner(OWNER)
            .with_to(TO)
            .with_input(Bytes::from(b"calldata"))
    }

    fn base_gst_builder() -> AutomatedTransactionBuilder {
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::GST)
            .with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID)
            .with_gas_limit(GAS_LIMIT)
            .with_gas_price_cap(GAS_PRICE_CAP)
            .with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX)
            .with_owner(OWNER)
            .with_to(TO)
            .with_input(Bytes::from(b"calldata"))
    }

    fn unwrap_success(r: BuildResult) -> AutomatedTransactionDetails {
        match r {
            BuildResult::Success(d) => d,
            other => panic!("expected BuildResult::Success, got {other:?}"),
        }
    }

    // ── TaskPredicate::try_from ───────────────────────────────────────────────

    #[test]
    fn predicate_from_empty_slice_returns_default() {
        let p = TaskPredicate::try_from([].as_slice()).unwrap();
        assert_eq!(p, TaskPredicate::default());
        assert_eq!(p.address, Address::ZERO);
        assert!(p.input.is_empty());
    }

    #[test]
    fn predicate_from_valid_bytes_decodes_correctly() {
        let pred_addr = address!("cccccccccccccccccccccccccccccccccccccccc");
        let encoded = encode_predicate(pred_addr, b"check_fn");
        let p = TaskPredicate::try_from(encoded.as_ref()).unwrap();
        assert_eq!(p.address, pred_addr);
        assert_eq!(p.input, Bytes::from(b"check_fn"));
    }

    #[test]
    fn predicate_from_invalid_bytes_returns_payload_decode_error() {
        let err = TaskPredicate::try_from([0xFF, 0x01, 0x02].as_slice()).unwrap_err();
        assert!(matches!(err, SupraExtensionError::PayloadDecode { .. }));
    }

    // ── AutomatedTransactionType::try_from ───────────────────────────────────

    #[test]
    fn txn_type_checks() {

        // 0 is UST
        assert_eq!(AutomatedTransactionType::try_from(0u8).unwrap(), AutomatedTransactionType::UST);
        // 1 is GST
        assert_eq!(AutomatedTransactionType::try_from(1u8).unwrap(), AutomatedTransactionType::GST);

        // Any other value is error
        for v in [2u8, 50, 255] {
            assert!(
                matches!(AutomatedTransactionType::try_from(v), Err(SupraExtensionError::InvalidAutomationTaskTypeValue(_))),
                "expected error for {v}"
            );
        }
    }

    // ── AutomatedTransaction::is_gasless ──────────────────────────────────────

    #[test]
    fn ust_is_not_gasless() {
        let txn = AutomatedTransaction { txn_type: AutomatedTransactionType::UST, ..Default::default() };
        assert!(!txn.is_gasless());
    }

    #[test]
    fn gst_is_gasless() {
        let txn = AutomatedTransaction { txn_type: AutomatedTransactionType::GST, ..Default::default() };
        assert!(txn.is_gasless());
    }

    // ── Transaction trait impl ────────────────────────────────────────────────

    #[test]
    fn transaction_trait_field_accessors() {
        let input_data = Bytes::from(b"calldata");
        let val = U256::from(999u64);
        let txn = AutomatedTransaction {
            block_height: BLOCK_HEIGHT,
            registration_hash: REG_HASH,
            sender: OWNER,
            txn_type: AutomatedTransactionType::UST,
            chain_id: CHAIN_ID,
            nonce: TASK_INDEX,
            gas_limit: GAS_LIMIT,
            max_fee_per_gas: GAS_PRICE,
            to: TO,
            value: val,
            access_list: AccessList::default(),
            input: input_data.clone(),
            predicate: AutomationTaskPredicate::Bypass,
        };

        assert_eq!(txn.chain_id(), Some(CHAIN_ID));
        assert_eq!(txn.nonce(), TASK_INDEX);
        assert_eq!(txn.gas_limit(), GAS_LIMIT);
        assert_eq!(txn.gas_price(), None);
        assert_eq!(txn.max_fee_per_gas(), GAS_PRICE);
        assert_eq!(txn.max_priority_fee_per_gas(), Some(0));
        assert_eq!(txn.max_fee_per_blob_gas(), None);
        assert_eq!(txn.priority_fee_or_price(), 0);
        assert!(txn.is_dynamic_fee());
        assert_eq!(txn.kind(), TxKind::Call(TO));
        assert!(!txn.is_create());
        assert_eq!(txn.value(), val);
        assert_eq!(txn.input(), &input_data);
        assert_eq!(txn.access_list(), Some(&AccessList::default()));
        assert_eq!(txn.blob_versioned_hashes(), None);
        assert_eq!(txn.authorization_list(), None);
    }

    #[test]
    fn effective_gas_price_no_base_fee_equals_max_fee() {
        let txn = AutomatedTransaction { max_fee_per_gas: 5_000, ..Default::default() };
        assert_eq!(txn.effective_gas_price(None), 5_000);
    }

    #[test]
    fn effective_gas_price_base_fee_below_max_fee_uses_base_fee() {
        let txn = AutomatedTransaction { max_fee_per_gas: 5_000, ..Default::default() };
        // min(5000, 100 + 0) = 100
        assert_eq!(txn.effective_gas_price(Some(100)), 100);
    }

    #[test]
    fn effective_gas_price_base_fee_above_max_fee_is_capped() {
        let txn = AutomatedTransaction { max_fee_per_gas: 1_000, ..Default::default() };
        // min(1000, 9999 + 0) = 1000
        assert_eq!(txn.effective_gas_price(Some(9_999)), 1_000);
    }

    // ── AutomatedTransactionDetails ordering ──────────────────────────────────

    fn make_details(txn_type: AutomatedTransactionType, priority: u64) -> AutomatedTransactionDetails {
        AutomatedTransactionDetails {
            txn: AutomatedTransaction { txn_type, ..Default::default() },
            priority,
        }
    }

    #[test]
    fn same_type_ordered_by_priority_ascending() {
        let low  = make_details(AutomatedTransactionType::UST, 1);
        let high = make_details(AutomatedTransactionType::UST, 10);
        assert!(low < high);
        assert!(high > low);
        assert_eq!(low.cmp(&low), std::cmp::Ordering::Equal);
    }

    #[test]
    fn ust_always_less_than_gst_regardless_of_priority() {
        let ust = make_details(AutomatedTransactionType::UST, 100);
        let gst = make_details(AutomatedTransactionType::GST, 1);
        assert!(ust < gst);
    }

    #[test]
    fn gst_always_greater_than_ust() {
        let ust = make_details(AutomatedTransactionType::UST, 0);
        let gst = make_details(AutomatedTransactionType::GST, u64::MAX);
        assert!(gst > ust);
    }

    // ── TaskPayload ───────────────────────────────────────────────────────────

    #[test]
    fn task_payload_from_valid_bytes_decodes_all_fields() {
        let expected_value = U256::from(42u64);
        let encoded = encode_payload(expected_value, TO, b"hello");
        let payload = TaskPayload::try_from(encoded.as_ref()).unwrap();
        assert_eq!(*payload.to(), TO);
        assert_eq!(*payload.value(), expected_value);
        assert_eq!(*payload.input(), Bytes::from(b"hello"));
        assert!(payload.access_list().0.is_empty());
    }

    #[test]
    fn task_payload_from_invalid_bytes_returns_error() {
        let err = TaskPayload::try_from([0xDE, 0xAD, 0xBE].as_slice()).unwrap_err();
        assert!(matches!(err, SupraExtensionError::PayloadDecode { .. }));
    }

    #[test]
    fn task_payload_random_produces_non_zero_address() {
        let payload = TaskPayload::random();
        assert_ne!(*payload.to(), Address::ZERO);
        assert_ne!(*payload.value(), U256::ZERO);
    }

    // ── AutomatedTransactionBuilder: successful UST build ─────────────────────

    #[test]
    fn build_ust_success_sets_all_fields() {
        let details = unwrap_success(base_ust_builder().build().unwrap());
        let txn = &details.txn;

        assert_eq!(txn.block_height, BLOCK_HEIGHT);
        assert_eq!(txn.registration_hash, REG_HASH);
        assert_eq!(txn.sender, OWNER);
        assert_eq!(txn.txn_type, AutomatedTransactionType::UST);
        assert_eq!(txn.chain_id, CHAIN_ID);
        assert_eq!(txn.nonce, TASK_INDEX);
        assert_eq!(txn.gas_limit, GAS_LIMIT);
        assert_eq!(txn.max_fee_per_gas, GAS_PRICE);
        assert_eq!(txn.to, TO);
        assert_eq!(details.priority, TASK_INDEX);
    }

    #[test]
    fn build_gst_defaults_gas_price_to_zero() {
        let details = unwrap_success(base_gst_builder().build().unwrap());
        assert_eq!(details.txn.max_fee_per_gas, 0);
        assert!(details.txn.is_gasless());
    }

    #[test]
    fn build_priority_defaults_to_task_index() {
        let details = unwrap_success(base_ust_builder().build().unwrap());
        assert_eq!(details.priority, TASK_INDEX);
    }

    #[test]
    fn build_explicit_priority_overrides_default() {
        let details = unwrap_success(base_ust_builder().with_priority(42).build().unwrap());
        assert_eq!(details.priority, 42);
    }

    #[test]
    fn build_without_predicate_sets_bypass() {
        let details = unwrap_success(base_ust_builder().build().unwrap());
        assert_eq!(details.txn.predicate, AutomationTaskPredicate::Bypass);
    }

    #[test]
    fn build_with_predicate_sets_predicate_variant() {
        let pred = TaskPredicate {
            address: address!("cccccccccccccccccccccccccccccccccccccccc"),
            input: Bytes::from(b"check"),
        };
        let details = unwrap_success(
            base_ust_builder().with_predicate(pred.clone()).build().unwrap()
        );
        assert_eq!(details.txn.predicate, AutomationTaskPredicate::Predicate(pred));
    }

    // ── AutomatedTransactionBuilder: gas price cap check ─────────────────────

    #[test]
    fn build_ust_gas_price_above_cap_returns_exceeded() {
        let result = base_ust_builder()
            .with_gas_price(3_000)
            .with_gas_price_cap(1_000)
            .build()
            .unwrap();
        match result {
            BuildResult::GasPriceLimitExceeded { task_index, value, threshold } => {
                assert_eq!(task_index, TASK_INDEX);
                assert_eq!(value, 3_000);
                assert_eq!(threshold, 1_000);
            }
            _ => panic!("expected GasPriceLimitExceeded"),
        }
    }

    #[test]
    fn build_ust_gas_price_equal_to_cap_returns_success() {
        let result = base_ust_builder()
            .with_gas_price(1_000)
            .with_gas_price_cap(1_000)
            .build()
            .unwrap();
        assert!(matches!(result, BuildResult::Success(_)));
    }

    #[test]
    fn build_ust_gas_price_below_cap_returns_success() {
        let result = base_ust_builder()
            .with_gas_price(500)
            .with_gas_price_cap(1_000)
            .build()
            .unwrap();
        assert!(matches!(result, BuildResult::Success(_)));
    }

    #[test]
    fn build_gst_ignores_gas_price_cap_check() {
        // GST gas_price is forced to 0 so even cap = 0 never triggers exceeded
        let result = base_gst_builder().with_gas_price_cap(0).build().unwrap();
        assert!(matches!(result, BuildResult::Success(_)));
    }

    // ── AutomatedTransactionBuilder: missing mandatory fields ─────────────────

    macro_rules! missing_field_test {
        ($name:ident, $builder:expr, $field:literal) => {
            #[test]
            fn $name() {
                let err = $builder.build().unwrap_err();
                assert!(
                    matches!(&err, SupraExtensionError::MissingBuilderValue(_, f) if f == $field),
                    "expected MissingBuilderValue for field {}, got {err:?}", $field
                );
            }
        };
    }

    missing_field_test!(build_missing_type_returns_error,
        AutomatedTransactionBuilder::new()
            .with_block_height(BLOCK_HEIGHT).with_chain_id(CHAIN_ID)
            .with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_to(TO)
            .with_input(Bytes::from(b"d")),
        "type"
    );

    missing_field_test!(build_missing_block_height_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_chain_id(CHAIN_ID)
            .with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_to(TO)
            .with_input(Bytes::from(b"d")),
        "block_height"
    );

    missing_field_test!(build_missing_chain_id_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_to(TO)
            .with_input(Bytes::from(b"d")),
        "chain_id"
    );

    missing_field_test!(build_missing_gas_limit_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_to(TO)
            .with_input(Bytes::from(b"d")),
        "gas_limit"
    );

    missing_field_test!(build_missing_gas_price_cap_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_registration_hash(REG_HASH).with_task_index(TASK_INDEX)
            .with_owner(OWNER).with_to(TO).with_input(Bytes::from(b"d")),
        "gas_price_cap"
    );

    missing_field_test!(build_ust_missing_gas_price_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_to(TO)
            .with_input(Bytes::from(b"d")),
        "gas_price"
    );

    missing_field_test!(build_missing_registration_hash_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_task_index(TASK_INDEX)
            .with_owner(OWNER).with_to(TO).with_input(Bytes::from(b"d")),
        "registration_hash"
    );

    missing_field_test!(build_missing_task_index_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_owner(OWNER).with_to(TO).with_input(Bytes::from(b"d")),
        "task_index"
    );

    missing_field_test!(build_missing_owner_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_to(TO).with_input(Bytes::from(b"d")),
        "owner"
    );

    missing_field_test!(build_missing_to_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_input(Bytes::from(b"d")),
        "to"
    );

    missing_field_test!(build_missing_input_returns_error,
        AutomatedTransactionBuilder::new()
            .with_typ(AutomatedTransactionType::UST).with_block_height(BLOCK_HEIGHT)
            .with_chain_id(CHAIN_ID).with_gas_limit(GAS_LIMIT).with_gas_price(GAS_PRICE)
            .with_gas_price_cap(GAS_PRICE_CAP).with_registration_hash(REG_HASH)
            .with_task_index(TASK_INDEX).with_owner(OWNER).with_to(TO),
        "input"
    );

    // ── TryFrom<TaskMetadata> ─────────────────────────────────────────────────

    #[test]
    fn task_metadata_pending_state_returns_error() {
        let metadata = base_task_metadata(0, 0); // Pending, UST
        let err = AutomatedTransactionBuilder::try_from(metadata).unwrap_err();
        assert!(matches!(err, SupraExtensionError::InvalidAutomationTaskStateForBuilder));
    }

    #[test]
    fn task_metadata_invalid_state_returns_error() {
        let metadata = base_task_metadata(3, 0); // invalid state
        let err = AutomatedTransactionBuilder::try_from(metadata).unwrap_err();
        assert!(matches!(err, SupraExtensionError::InvalidAutomationTaskStateValue(3)));
    }

    #[test]
    fn task_metadata_invalid_type_returns_error() {
        let metadata = base_task_metadata(1, 5); // Active, invalid type
        let err = AutomatedTransactionBuilder::try_from(metadata).unwrap_err();
        assert!(matches!(err, SupraExtensionError::InvalidAutomationTaskTypeValue(5)));
    }

    #[test]
    fn task_metadata_active_ust_produces_correct_builder_fields() {
        let metadata = base_task_metadata(1, 0); // Active, UST
        let builder = AutomatedTransactionBuilder::try_from(metadata).unwrap();
        assert_eq!(*builder.task_index(), Some(TASK_INDEX));
        assert_eq!(*builder.gas_limit(), Some(GAS_LIMIT));
        assert_eq!(*builder.gas_price_cap(), Some(GAS_PRICE_CAP));
        assert_eq!(*builder.owner(), Some(OWNER));
        assert!(matches!(builder.typ(), Some(AutomatedTransactionType::UST)));
        assert_eq!(*builder.to(), Some(TO));
    }

    #[test]
    fn task_metadata_cancelled_gst_sets_correct_type() {
        let metadata = base_task_metadata(2, 1); // Cancelled, GST
        let builder = AutomatedTransactionBuilder::try_from(metadata).unwrap();
        assert!(matches!(builder.typ(), Some(AutomatedTransactionType::GST)));
    }

    #[test]
    fn task_metadata_with_predicate_propagates_to_builder() {
        let pred_addr = address!("dddddddddddddddddddddddddddddddddddddddd");
        let mut metadata = base_task_metadata(1, 0);
        metadata.predicate = encode_predicate(pred_addr, b"pred_input");
        let builder = AutomatedTransactionBuilder::try_from(metadata).unwrap();
        let predicate = builder.predicate().as_ref().unwrap();
        assert_eq!(predicate.address, pred_addr);
        assert_eq!(predicate.input, Bytes::from(b"pred_input"));
    }

    #[test]
    fn task_metadata_empty_predicate_produces_default_predicate_in_builder() {
        // Empty predicate bytes → TaskPredicate::default() (address=ZERO, input=empty)
        // which is stored as Some(TaskPredicate::default()) in the builder
        let metadata = base_task_metadata(1, 0);
        let builder = AutomatedTransactionBuilder::try_from(metadata).unwrap();
        assert_eq!(*builder.predicate(), Some(TaskPredicate::default()));
    }

    #[test]
    fn task_metadata_invalid_payload_returns_error() {
        let mut metadata = base_task_metadata(1, 0);
        metadata.payloadTx = Bytes::from(b"not_valid_abi");
        let err = AutomatedTransactionBuilder::try_from(metadata).unwrap_err();
        assert!(matches!(err, SupraExtensionError::PayloadDecode { .. }));
    }

    #[test]
    fn task_metadata_invalid_predicate_returns_error() {
        let mut metadata = base_task_metadata(1, 0);
        metadata.predicate = Bytes::from(b"not_valid_abi");
        let err = AutomatedTransactionBuilder::try_from(metadata).unwrap_err();
        assert!(matches!(err, SupraExtensionError::PayloadDecode { .. }));
    }

    #[test]
    fn task_metadata_active_ust_full_build_succeeds() {
        let metadata = base_task_metadata(1, 0);
        let details = unwrap_success(
            AutomatedTransactionBuilder::try_from(metadata)
                .unwrap()
                .with_block_height(BLOCK_HEIGHT)
                .with_chain_id(CHAIN_ID)
                .with_gas_price(GAS_PRICE)
                .build()
                .unwrap(),
        );
        assert_eq!(details.txn.txn_type, AutomatedTransactionType::UST);
        assert_eq!(details.txn.to, TO);
        assert_eq!(details.txn.nonce, TASK_INDEX);
    }

    #[test]
    fn check_payload_decode() {
        let encoded = hex!("00000000000000000000000000000000000000000000000000000000000000000000000000000000000000006b182f1488e8efeb2eb298155ed5bd7ff8a14042000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000242e1a7d4d0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000001111000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000022220000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001");
        let (value, to, input, access_list) = ExpandedPayloadTy::abi_decode(&encoded).unwrap();
        println!("to: {:?}", to);
        println!("value: {:?}", value);
        println!("access_list: {:?}", access_list);
        println!("input: {:?}", input);
    }

    #[test]
    fn check_predicate_decode() {
        let encoded = hex!("000000000000000000000000d3e2a56659d5113fa44c3d09dc21ea8ff48452570000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000426a7076400000000000000000000000000000000000000000000000000000000");
        let payload = TaskPredicate::try_from(encoded.as_slice()).unwrap();
        println!("to: {:?}", payload.address);
        println!("input: {:?}", payload.input);
    }
}
