//! AutomatedTransaction generated based on the registered active automation task.

use crate::errors::SupraExtensionError;
use crate::value_or_error;
use crate::TaskMetadata;
use alloy::eips::eip2930::AccessList;
use alloy::primitives::{Address, Bytes, ChainId, B256, U256};
use alloy_consensus::transaction::Transaction;
use alloy_eips::eip2718::Typed2718;
use alloy_sol_types::SolType;
use context::transaction::{AccessListItem, SignedAuthorization};
use context::TransactionType;
use derive_getters::{Dissolve, Getters};
use derive_more::Constructor;
use primitives::TxKind;
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
#[repr(u8)]
/// Automated transaction type corresponding automation task type.
pub enum AutomatedTransactionType {
    /// User submitted automation task based
    #[default]
    UST = 0,
    /// Governance submitted/authorized automation task based. Will be gasless transaction
    GST,
}

impl TryFrom<u8> for AutomatedTransactionType {
    type Error = SupraExtensionError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::UST),
            1 => Ok(Self::GST),
            _ => Err(Self::Error::InvalidAutomationTaskTypeValue(value)),
        }
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "camelCase"))]
/// Automated transaction generated by node runtime based on the registered active automation task.
pub struct AutomatedTransaction {
    /// Height of the block in scope of which this transaction is being executed.
    pub block_height: u64,
    /// Hash of the transaction which registered an automation task based on which this transaction is created.
    pub registration_hash: B256,
    /// Owner address of the automation task, the source of this transaction.
    pub sender: Address,
    /// Type of the automated transaction.
    pub txn_type: AutomatedTransactionType,
    /// Chain id.
    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity"))]
    pub chain_id: ChainId,
    /// A scalar value equal to the automation task index based on which this transaction is created.
    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity"))]
    pub nonce: u64,
    /// A scalar value equal to the maximum
    /// amount of gas that should be used in executing
    /// this transaction. This is paid up-front, before any
    /// computation is done and may not be increased
    /// later; formally Tg.
    #[cfg_attr(
        feature = "serde",
        serde(with = "alloy_serde::quantity", rename = "gas", alias = "gasLimit")
    )]
    pub gas_limit: u64,
    /// A scalar value equal to the maximum
    /// amount of gas that should be used in executing
    /// this transaction.
    #[cfg_attr(feature = "serde", serde(with = "alloy_serde::quantity"))]
    pub max_fee_per_gas: u128,
    /// The 160-bit address of the message call’s recipient or, for a contract creation
    /// transaction, ∅, used here to denote the only member of B0 ; formally Tt.
    #[cfg_attr(feature = "serde", serde(default))]
    pub to: Address,
    /// A scalar value equal to the number of Wei to
    /// be transferred to the message call’s recipient or,
    /// in the case of contract creation, as an endowment
    /// to the newly created account; formally Tv.
    pub value: U256,
    /// The accessList specifies a list of addresses and storage keys;
    /// these addresses and storage keys are added into the `accessed_addresses`
    /// and `accessed_storage_keys` global sets (introduced in EIP-2929).
    /// A gas cost is charged, though at a discount relative to the cost of
    /// accessing outside the list.
    // Deserialize with `alloy_serde::null_as_default` to also accept a `null` value
    // instead of an (empty) array. This is due to certain RPC providers (e.g., Filecoin's)
    // sometimes returning `null` instead of an empty array `[]`.
    // More details in <https://github.com/alloy-rs/alloy/pull/2450>.
    #[cfg_attr(
        feature = "serde",
        serde(deserialize_with = "alloy_serde::null_as_default")
    )]
    pub access_list: AccessList,
    /// Input: An unlimited size byte array specifying the
    /// input data of the message call.
    pub input: Bytes,
}

impl Transaction for AutomatedTransaction {
    #[inline]
    fn chain_id(&self) -> Option<ChainId> {
        Some(self.chain_id)
    }

    #[inline]
    fn nonce(&self) -> u64 {
        self.nonce
    }

    #[inline]
    fn gas_limit(&self) -> u64 {
        self.gas_limit
    }

    #[inline]
    fn gas_price(&self) -> Option<u128> {
        None
    }

    #[inline]
    fn max_fee_per_gas(&self) -> u128 {
        self.max_fee_per_gas
    }

    #[inline]
    fn max_priority_fee_per_gas(&self) -> Option<u128> {
        Some(0)
    }

    #[inline]
    fn max_fee_per_blob_gas(&self) -> Option<u128> {
        None
    }

    #[inline]
    fn priority_fee_or_price(&self) -> u128 {
        0
    }

    fn effective_gas_price(&self, base_fee: Option<u64>) -> u128 {
        alloy_eips::eip1559::calc_effective_gas_price(self.max_fee_per_gas, 0, base_fee)
    }

    #[inline]
    fn is_dynamic_fee(&self) -> bool {
        true
    }

    #[inline]
    fn kind(&self) -> TxKind {
        TxKind::Call(self.to)
    }

    #[inline]
    fn is_create(&self) -> bool {
        false
    }

    #[inline]
    fn value(&self) -> U256 {
        self.value
    }

    #[inline]
    fn input(&self) -> &Bytes {
        &self.input
    }

    #[inline]
    fn access_list(&self) -> Option<&AccessList> {
        Some(&self.access_list)
    }

    #[inline]
    fn blob_versioned_hashes(&self) -> Option<&[B256]> {
        None
    }

    #[inline]
    fn authorization_list(&self) -> Option<&[SignedAuthorization]> {
        None
    }
}

impl Typed2718 for AutomatedTransaction {
    fn ty(&self) -> u8 {
        TransactionType::Custom as u8
    }
}

impl AutomatedTransaction {
    /// Returns true if automated transaction is gas-less, otherwise false.
    /// GST type transactions are considered as gas-less.
    pub fn is_gasless(&self) -> bool {
        matches!(self.txn_type, AutomatedTransactionType::GST)
    }
}

/// Evm automated transaction with priority to be scheduled for execution.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct AutomatedTransactionDetails {
    /// Transaction details
    pub txn: AutomatedTransaction,
    /// Priority of the automated transaction to be scheduled.
    /// The low value indicates higher priority.
    pub priority: u64,
}

impl Ord for AutomatedTransactionDetails {
    fn cmp(&self, other: &Self) -> Ordering {
        let left_type = &self.txn.txn_type;
        let right_type = &other.txn.txn_type;
        if left_type == right_type {
            self.priority.cmp(&other.priority)
        } else {
            left_type.cmp(right_type)
        }
    }
}
impl PartialOrd for AutomatedTransactionDetails {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

type AccessListItemTy = (
    alloy_sol_types::sol_data::Address,
    alloy_sol_types::sol_data::Array<alloy_sol_types::sol_data::FixedBytes<32>>,
);
type AccessListTy = alloy_sol_types::sol_data::Array<AccessListItemTy>;
type ExpandedPayloadTy = (
    alloy_sol_types::sol_data::Uint<256>,
    alloy_sol_types::sol_data::Address,
    alloy_sol_types::sol_data::Bytes,
    AccessListTy,
);

/// Evm automation task execution payload.
#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    Getters,
    Dissolve,
    Constructor,
)]
pub struct TaskPayload {
    to: Address,
    value: U256,
    input: Bytes,
    access_list: AccessList,
}

impl TaskPayload {
    /// Generates random [`TaskPayload`] for testing propose only.
    pub fn random() -> Self {
        TaskPayload {
            to: Address::random(),
            value: U256::random(),
            input: Bytes::from(b"test"),
            access_list: AccessList::default(),
        }
    }
}

impl TryFrom<&[u8]> for TaskPayload {
    type Error = SupraExtensionError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        let (value, to, input, access_list) = ExpandedPayloadTy::abi_decode(value)?;
        let access_items = access_list
            .into_iter()
            .map(|(address, storage_keys)| AccessListItem {
                address,
                storage_keys,
            })
            .collect();
        Ok(Self {
            to,
            value,
            access_list: AccessList(access_items),
            input,
        })
    }
}

/// Automation task state in native layer
#[derive(Clone, Debug, PartialEq, Eq)]
#[repr(u8)]
enum AutomationTaskState {
    Pending = 0,
    Active = 1,
    Cancelled = 2,
}

impl TryFrom<u8> for AutomationTaskState {
    type Error = SupraExtensionError;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Pending),
            1 => Ok(Self::Active),
            2 => Ok(Self::Cancelled),
            _ => Err(SupraExtensionError::InvalidAutomationTaskStateValue(value)),
        }
    }
}

/// [`AutomatedTransactionBuilder`] result
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BuildResult {
    /// Success result wrapping [`AutomatedTransactionDetails`]
    Success(AutomatedTransactionDetails),
    /// Build failure due to gas-price limit surpass.
    GasPriceLimitExceeded {
        /// Task index for which error is observed.
        task_index: u64,
        /// Gas price specified for the transaction.
        value: u128,
        /// Gas price threshold specified for the automation task during registration.
        threshold: u128,
    },
}

/// Builder for [`AutomatedTransactionDetails`]
/// All properties are mandatory to be set for successful automated transaction build.
/// The following values fall back to agreed defaults if not specified:
///   - priority - defaults to task-index
///   - access_list - default to empty access-list
///   - value - defaults to 0
#[derive(Clone, Debug, Getters)]
pub struct AutomatedTransactionBuilder {
    block_height: Option<u64>,
    chain_id: Option<ChainId>,
    gas_limit: Option<u64>,
    gas_price: Option<u128>,
    gas_price_cap: Option<u128>,
    registration_hash: Option<B256>,
    task_index: Option<u64>,
    expiry_timestamp: Option<u64>,
    owner: Option<Address>,
    typ: Option<AutomatedTransactionType>,
    priority: Option<u64>,

    to: Option<Address>,
    value: Option<U256>,
    access_list: Option<AccessList>,
    input: Option<Bytes>,
}

#[allow(missing_docs)]
impl AutomatedTransactionBuilder {
    pub fn new() -> Self {
        Self {
            block_height: None,
            chain_id: None,
            gas_limit: None,
            gas_price: None,
            gas_price_cap: None,
            registration_hash: None,
            task_index: None,
            expiry_timestamp: None,
            owner: None,
            typ: None,
            priority: None,
            to: None,
            value: Some(U256::from(0)),
            access_list: Some(AccessList::default()),
            input: None,
        }
    }

    pub fn with_block_height(mut self, block_height: u64) -> Self {
        self.block_height = Some(block_height);
        self
    }

    pub fn with_chain_id(mut self, chain_id: ChainId) -> Self {
        self.chain_id = Some(chain_id);
        self
    }

    pub fn with_gas_limit(mut self, gas_limit: u64) -> Self {
        self.gas_limit = Some(gas_limit);
        self
    }
    pub fn with_gas_price(mut self, gas_price: u128) -> Self {
        self.gas_price = Some(gas_price);
        self
    }
    pub fn with_gas_price_cap(mut self, gas_price_cap: u128) -> Self {
        self.gas_price_cap = Some(gas_price_cap);
        self
    }
    pub fn with_registration_hash(mut self, registration_hash: B256) -> Self {
        self.registration_hash = Some(registration_hash);
        self
    }
    pub fn with_task_index(mut self, task_index: u64) -> Self {
        self.task_index = Some(task_index);
        self
    }
    pub fn with_expiry_timestamp(mut self, expiry_timestamp: u64) -> Self {
        self.expiry_timestamp = Some(expiry_timestamp);
        self
    }
    pub fn with_owner(mut self, owner: Address) -> Self {
        self.owner = Some(owner);
        self
    }
    pub fn with_typ(mut self, typ: AutomatedTransactionType) -> Self {
        self.typ = Some(typ);
        self
    }
    pub fn with_priority(mut self, priority: u64) -> Self {
        self.priority = Some(priority);
        self
    }
    pub fn with_to(mut self, to: Address) -> Self {
        self.to = Some(to);
        self
    }
    pub fn with_value(mut self, value: U256) -> Self {
        self.value = Some(value);
        self
    }
    pub fn with_access_list(mut self, access_list: AccessList) -> Self {
        self.access_list = Some(access_list);
        self
    }
    pub fn with_input(mut self, input: Bytes) -> Self {
        self.input = Some(input);
        self
    }
    pub fn build(self) -> Result<BuildResult, SupraExtensionError> {
        let Self {
            block_height,
            chain_id,
            gas_limit,
            gas_price,
            gas_price_cap,
            registration_hash,
            task_index,
            expiry_timestamp: _,
            owner,
            typ,
            priority,
            to,
            value,
            access_list,
            input,
        } = self;
        let typ = value_or_error!(AutomatedTransactionBuilder, "type", typ);
        let block_height =
            value_or_error!(AutomatedTransactionBuilder, "block_height", block_height);
        let chain_id = value_or_error!(AutomatedTransactionBuilder, "chain_id", chain_id);
        let gas_limit = value_or_error!(AutomatedTransactionBuilder, "gas_limit", gas_limit);
        let gas_price_cap =
            value_or_error!(AutomatedTransactionBuilder, "gas_price_cap", gas_price_cap);
        // GST based automated transaction are not charged, so the gas price is not mandatory and default to 0.
        let gas_price = match typ {
            AutomatedTransactionType::UST => {
                value_or_error!(AutomatedTransactionBuilder, "gas_price", gas_price)
            }
            AutomatedTransactionType::GST => 0,
        };
        let registration_hash = value_or_error!(
            AutomatedTransactionBuilder,
            "registration_hash",
            registration_hash
        );
        let task_index = value_or_error!(AutomatedTransactionBuilder, "task_index", task_index);
        let owner = value_or_error!(AutomatedTransactionBuilder, "owner", owner);
        let priority = priority.unwrap_or(task_index);
        let to = value_or_error!(AutomatedTransactionBuilder, "to", to);
        let value = value_or_error!(AutomatedTransactionBuilder, "value", value);
        let access_list = value_or_error!(AutomatedTransactionBuilder, "access_list", access_list);
        let input = value_or_error!(AutomatedTransactionBuilder, "input", input);
        if typ == AutomatedTransactionType::UST && gas_price_cap < gas_price{
            return Ok(BuildResult::GasPriceLimitExceeded {
                task_index,
                value: gas_price,
                threshold: gas_price_cap,
            });
        }
        let txn = AutomatedTransaction {
            block_height,
            registration_hash,
            sender: owner,
            txn_type: typ,
            chain_id,
            nonce: task_index,
            gas_limit,
            max_fee_per_gas: gas_price,
            to,
            value,
            access_list,
            input,
        };
        Ok(BuildResult::Success(AutomatedTransactionDetails {
            txn,
            priority,
        }))
    }
}

/// Constructs [`AutomatedTransactionBuilder`] from automation task details loaded from chain state.
/// Fails if:
///   - inner payload cannot be deserialized based on the  [`ExpandedPayloadTy`] schema
///   - Loaded task is not in active state (Active | Cancelled)
impl TryFrom<TaskMetadata> for AutomatedTransactionBuilder {
    type Error = SupraExtensionError;

    fn try_from(value: TaskMetadata) -> Result<Self, Self::Error> {
        let TaskMetadata {
            maxGasAmount,
            gasPriceCap,
            automationFeeCapForCycle: _,
            depositFee: _,
            txHash,
            taskIndex,
            registrationTime: _,
            expiryTime,
            priority,
            taskType,
            owner,
            taskState,
            payloadTx,
            // TODO: handle predicate
            predicate: _,
            auxData: _,
        } = value;

        if AutomationTaskState::try_from(taskState)? == AutomationTaskState::Pending {
            return Err(SupraExtensionError::InvalidAutomationTaskStateForBuilder);
        }
        let typ = AutomatedTransactionType::try_from(taskType)?;

        let (to, value, input, access_list) = TaskPayload::try_from(payloadTx.as_ref())?.dissolve();
        let builder = Self::new()
            .with_gas_price_cap(gasPriceCap)
            .with_gas_limit(maxGasAmount as u64)
            .with_gas_price_cap(gasPriceCap)
            .with_registration_hash(txHash)
            .with_task_index(taskIndex)
            .with_expiry_timestamp(expiryTime)
            .with_owner(owner)
            .with_to(to)
            .with_value(value)
            .with_input(input)
            .with_access_list(access_list)
            .with_typ(typ)
            .with_priority(priority);
        Ok(builder)
    }
}

#[cfg(test)]
mod test {
    use crate::transactions::automated_transaction::ExpandedPayloadTy;
    use alloy::hex;
    use alloy_sol_types::SolType;
    #[test]
    fn check_payload_decode() {
        let encoded = hex!("00000000000000000000000000000000000000000000000000000000000000000000000000000000000000006b182f1488e8efeb2eb298155ed5bd7ff8a14042000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000242e1a7d4d0000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000001111000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000022220000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001");
        let (value, to, input, access_list) = ExpandedPayloadTy::abi_decode(&encoded).unwrap();
        println!("to: {:?}", to);
        println!("value: {:?}", value);
        println!("access_list: {:?}", access_list);
        println!("input: {:?}", input);
    }
}
