[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
evm_version = "prague"
# Uncomment when running agains supra chain

#eth_rpc_url = "http://localhost:27000/rpc/v1/eth/wallet_integration"

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


