dapp_path = "../../solidity/supra_contracts/"

contract_names = [
    "MultiSignatureWallet",
    "MultisigBeacon",
    "BeaconProxy",
    "WrappedSupra",
    "BlockMeta",
    "ERC1967Proxy",
    "DiamondCutFacet",
    "Diamond",
    "DiamondLoupeFacet",
    "OwnershipFacet",
    "ConfigFacet",
    "RegistryFacet",
    "CoreFacet",
    "DiamondInit",
]

