#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all, dead_code, unreachable_pub)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub(crate) mod r#supra_contracts_bindings;
